# See https://github.com/codecov/support/wiki/Codecov-Yaml
codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: 80..100
  status:
    patch:
      default:
        target: 100%
    project:
      default:
        target: auto
        threshold: 0.05
      tests:
        target: 100%
        paths:
          - "ldaptor/test/test_*"
