#!/bin/sh
set -e

for POT in po/*.pot; do
    DOMAIN="$(basename "$POT" .pot)"

    find "po/$DOMAIN" -name '*.po' \
	| while read PO; do
	LOC="$(basename "$PO" .po)"
	install -d -m0755 "locale/$LOC/LC_MESSAGES"
	msgfmt -o "locale/$LOC/LC_MESSAGES/$DOMAIN.mo" "$PO"
    done
done
