#!/bin/sh
set -e

export COVERAGE_FILE="$PWD/coverage"
export PYTHONPATH=.

PYTHON=python2.3

$PYTHON admin/coverage.py -e

$PYTHON admin/coverage.py -x /usr/bin/trial -R ldaptor || true

find ldaptor -name '*.py' -print0 \
    | xargs -0 --no-run-if-empty $PYTHON admin/coverage.py -a -r

rm coverage
